GTNewHorizons/Hodgepodge

README.md
src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/speedupChunkCoordinatesHashCode/MixinChunkCoordinates.java

Provides better results with HashSet()

Speedup ChunkCoordinates.hashCode

---

addon.gradle
build.gradle
src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
src/main/java/com/mitchej123/hodgepodge/mixins/fixIc2Nightvision/MixinIc2NightVisionGoggles.java

Apparently there's another ic2 item that gives night vision and that's what EMT was using for the nanosuit goggles of revealing...  Fixes #20

Fix EMT Nightvision

---

build.gradle
dependencies.gradle
gradle.properties

Update build script and switch to in-house dependencies

---

src/main/java/com/mitchej123/hodgepodge/mixins/speedupVanillaFurnace/MixinFurnaceRecipes.java

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9068

Ec2 why you crash

---

src/main/java/com/mitchej123/hodgepodge/asm/InventoryEffectRendererTransformer.java
src/main/java/com/mitchej123/hodgepodge/asm/PollutionClassTransformer.java
src/main/java/com/mitchej123/hodgepodge/asm/util/AbstractClassTransformer.java

Should speed up classloading a bit

Do not blindly parse every and single class

---

src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/mixinWorld/fixGetBlock.java

Fix getBlock call on null chunks
Meh, RC jar changed; need a less brittle fix for this

Fix GetBlocks & RC Jar Update

---

src/main/java/com/mitchej123/hodgepodge/asm/BibliocraftTransformer.java
src/main/java/com/mitchej123/hodgepodge/asm/HodgePodgeASMLoader.java
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java

closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9198

Another sledgehammer

---

src/main/java/com/mitchej123/hodgepodge/core/util/ItemStackMap.java

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9203
Vanilla's method compares getItem() and getItemDamage() only.

Ignore NBT tags in furnace recipe lookup

---

src/main/java/com/mitchej123/hodgepodge/asm/BibliocraftTransformer.java

per  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9254

Expand sledgehammer

---

gradle.properties
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityPlayerMP.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinServerConfigurationManager.java

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7998

Fixes losing hearts when changing dimensions, especially when returning from the end.

---

src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinBlockHopper.java

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9299

Add a failsafe in hopper ray tracing

---

build.gradle
jitpack.yml

Jitpack bs

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/ic2/MixinItemIC2FluidContainer.java

closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10110

Display fluid localized name in IC2 fluid cell tooltip

---

build.gradle
dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/biomesoplenty/MixinBlockBOPSapling.java
src/main/java/com/mitchej123/hodgepodge/mixins/biomesoplenty/MixinFogHandler.java
src/main/java/com/mitchej123/hodgepodge/mixins/biomesoplenty/MixinForestryIntegration.java
src/main/java/com/mitchej123/hodgepodge/mixins/thaumcraft/MixinTileWandPedestal.java

- Update buildscript and add BOP as dependency
- Deduplicate BOP/Forestry compat (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/2886)
- Speedup biome fog handling
- Make big fir trees plantable via 5 saplings

BiomesOPlenty fixes

---

src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinTileEntityHopper.java

Fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10283

Fix hopper extract items from the disallowed side

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinS02PacketChat.java

Used to diagnose problems in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10207. Still a useful feature regardless.

Prevent kicking the player if he is to receive a huge chat message

---

.github/workflows/build-and-test.yml
README.md
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft.java

Imlement https://bugs.mojang.com/browse/MC-68754?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

Fix WindowsDisplay not resetting resizable

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/ic2/MixinTileEntityReactorChamberElectricInvSpeedup.java
src/main/java/com/mitchej123/hodgepodge/mixins/ic2/MixinTileEntityReactorChamberElectricNoDupe.java

otherwise it lags hard if you try to do item IO very frequently

add master tile cache to ic2 reactor

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/gregtech/textures/MixinGT_GeneratedMaterial_Renderer.java
src/main/java/com/mitchej123/hodgepodge/mixins/ic2/textures/MixinRenderLiquidCell.java

this is but a bandaid fix. a proper fix is warranted. with stable coming soon even a bandaid fix would help.
Fluid#getIcon probably is a better injection point, but that's not a final method and subclass might override it...

fix animation of fluid in cell for the two most common fluid cell

---

addon.gradle
src/main/java/com/mitchej123/hodgepodge/asm/EarlyASMCallHooks.java
src/main/java/com/mitchej123/hodgepodge/asm/EarlyClassTransformer.java
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/forge/MixinASMDataTable.java

these patches provide a grand total of ~6 second boost on my PC. For reference, it takes around 190~200 second to load the full pack on my PC.

various patches to optimize loading time

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityRenderer.java

Prevent tall grass and such to affect the perspective camera

---

src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinTcpNoDelay.java

* Taken from makamys/CoreTweaks, inspired by various other 1.7.10 mods, and the change in 1.8+
Ran this on my local MP setup without issue.

Add TCP_NO_DELAY

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft_ToggleDebugMessage.java

Add a debug message in the chat when toggling vanilla debug options

---

src/main/java/com/mitchej123/hodgepodge/core/util/RenderDebugHelper.java

Source of FPS lag found in RC1

turn off GL state recording when mode is off

---

src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft_ToggleDebugMessage.java

add message when reloading chunks

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/forge/MixinGuiIngameForge.java

hide crosshair in third person

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityLivinBase_HidePotionParticles.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityLivingBase_FixPotionException.java

it's annoying and obstructs the field of view, some players end up taking off their adventure backpack just because of this

option to not render potion particles from yourself

---

src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinDimensionManager.java

To help investigating the causes of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10377 or https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11271 or similar

Add debug logging for DimensionManager crash

---

dependencies.gradle
gradle.properties
src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/extrautilities/MixinRecipeUnEnchanting.java

Close https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/69

Fix Extra Utilities UnEnchanting

---

build.gradle
gradle.properties

These indicate which mods Hodgepdge is compatible with

Add optional CF Dependencies

---

build.gradle
src/main/java/com/mitchej123/hodgepodge/Compat.java
src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java

Adds a side check that was missing from #142.
(The CI fails because the master branch still has the old buildscript, the mod compiles fine locally.)

Fix Compat class crashing on server

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorld_FixLightUpdateLag.java

mixin backport of the following forge fix https://github.com/MinecraftForge/MinecraftForge/pull/4729

Fix too early light initialization

---

.github/workflows/build-and-test.yml
build.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java

Bug trigger:
- Bind both IC2 control key and vanilla Sprint key to LCONTROL
- Try to sprint with LCONTROL
Before the fix: nothing happens
After the fix: you can sprint, and ic2 can detect the control press too

Trigger all conflicting key bindings instead of a random one

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/hungeroverhaul/MixinHungerOverhaulModuleHarvestCraft.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5497

Fix some items restore 0 hunger due to Hunger Overhaul

---

build.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinVillage.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinVillageCollection.java

Inspired by Born in a Barn https://www.curseforge.com/minecraft/mc-mods/born-in-a-barn

Fix villages keeping things chunkloaded.

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldClient.java

when you load a world sometimes you get a huge sound that gives you a heart attack, this sound comes from minecarts getting placed in the wold. This mixin just removes the sound it plays when spawning a minecart in the world

stop playing a sound when spawning a minecart in the world

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinFontRenderer.java

Closes <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12718>

Replace recursive line wrapping with iterative code, and prevent infinite loops.

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinGuiFocalManipulator.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinGuiResearchRecipe.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinGuiResearchTable.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinGuiThaumatorium.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinItem_SortAspectsByName.java
src/main/java/com/mitchej123/hodgepodge/util/AspectNameSorter.java

Partially addresses https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12786

Fix Thaumcraft Aspect sorting

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinTextureAtlasSprite.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinTextureMap.java
src/main/java/com/mitchej123/hodgepodge/textures/IPatchedTextureAtlasSprite.java

Context: https://discord.com/channels/181078474394566657/603348502637969419/1088577224300576798

fix rare different sprite animations out of sync 

---

build.gradle
dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockBed.java

Show bed messages above hotbar

---

build.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/FluidContainerRegistryAccessor.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinFluidRegistry.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinEntityGolemBase.java

Same cause as https://github.com/GTNewHorizons/GT5-Unofficial/pull/2057
Fix Railcraft machines not interacting well with creosote / steam registered by GT

Fix fluid container registry key not being reloaded after world load

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/biomesoplenty/MixinBOPReflectionHelper.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/lotr/MixinLOTRLogReflection.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/lotr/MixinRedirectHuornAI.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/lotr/MixinRemoveUnlockFinalField.java
src/main/java/com/mitchej123/hodgepodge/util/FinalValueHelper.java

Hopefully temporary measures to get lotr working in newer java versions, taken from [my own mod](https://github.com/mist475/MistLotrTweaks) for convenience.

Lotr java 12+ patches & move MixinBOPReflectionHelper.setPrivateFinalValue logic to util class for reusablility

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinForgeVersion_FixUpdateCheck.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinForgeVersion_FixUpdateCheck.java

Replace the forge version check url with an https version

fix forge update checker

---

build.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorHazmat.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorJetpack.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorNanoSuit.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorNightvisionGoggles.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorQuantumSuit.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorSolarHelmet.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ArmorStaticBoots.java

`detectAndSendChanges` is executed on every tick by `EntityPlayerMP#onUpdate` anyway
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12520

Fix IC2 armors spamming detectAndSendChanges

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinFontRenderer.java

Fix color formatting in wrapFormattedStringToWidth mixin.
Before:
After:

Fix color formatting in FontRenderer mixin

---

build.gradle
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinItemGolemBell.java

Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13950

Fix crash when placing Thaumcraft Golem

---

gradle.properties
src/main/java/com/mitchej123/hodgepodge/common/KeyBindingDuck.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlock_FixXray.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_UpdateKeys.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorld_FixXray.java
src/main/java/com/mitchej123/hodgepodge/mixins/hooks/ThaumcraftMixinMethods.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/BlockExt_FixXray.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/KeyBindingExt.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinEntityGolemBase.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinItemGolemBell.java
src/main/resources/mixins.hodgepodge.json

move mixin related hooks and interfaces under mixin package

Refactor mixin package

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/betterhud/MixinHealthRender.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/betterhud/MixinSkullDurabilityDisplay.java

Although BetterHUD is MIT the only 1.7.10 [source code](https://github.com/mccreery/better-hud/commit/6221fddf7cef9b9f9388087386a00bc73019c6e3) is of a much older version of the mod. Hence the mixins

Fix BetterHUD freeze & rendering error

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2ItemCell.java

Give it a GregTech like behavior.

Give IC2 cells container items as GT cells do

---

.gitignore
build.gradle
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java

Restore creative search if NEI is not loaded

---

src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinRenderBlocks.java

* Disable some mixins with Angelica loaded until they're moved to Angelica

Angelica Compat

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/asm/AsmTransformers.java
src/main/java/com/mitchej123/hodgepodge/asm/transformers/optifine/GLErrorLoggingTransformer.java

Confirmed working when running the modified Complementary Shaders that Sampsa uses.

Remove annoying `GL error` message from Optifine/Shadersmod

---

src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java

* Disable some mixins with Angelica loaded until they're moved to Angelica

More Angelica Compat

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java

This reverts commit eb08425adc33ae61c50676e768d0b9a1fdae6161.
It stopped me from being able to click.... :fail:

Revert "Check for >0 instead of !=0"

---

src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiMainMenu_DisableRealmsButton.java

Add Disable Realms Button Mixin

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiMainMenu_DisableRealmsButton.java

Completely hide realms button and make mods button wider to fill the gap

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockHopper.java

How does nobody notice this for over a year and a half?

Fix hopper collision

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinTextureUtil.java

Had a resource pack with some 4x4 textures that wouldn't load on mipmap level 4. I fixed that and another bug I found in the process.

Fix some Mipmapping bugs

---

src/main/java/com/mitchej123/hodgepodge/client/HodgepodgeClient.java
src/main/java/com/mitchej123/hodgepodge/client/handlers/ClientKeyListener.java
src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_FastBlockPlacing.java
src/main/resources/assets/hodgepodge/lang/en_US.lang

Recreated the logic behind https://www.curseforge.com/minecraft/mc-mods/better-placement and put it behind a keybind
See https://discord.com/channels/181078474394566657/603348502637969419/1204543419788165140 for video preview

Fast Block Placing

---

src/main/java/com/mitchej123/hodgepodge/client/chat/ChatHandler.java
src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockRedstoneTorch.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_FastBlockPlacing.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal_FixWordLeak.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldClient_FixAllocations.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldServer_FixAllocations.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorld_FixAllocations.java

- use proper `@SuppressWarnings`
- enable replaceVoxelMapReflection by default
- add missing generics
- add missing `remap = false`
- add modID to VOXELMAP TargetedMod

Small Cleanup

---

README.md
src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java

Update README.md + required gtnhlib

---

src/main/resources/assets/hodgepodge/lang/en_US.lang

Add color to Fast Block Placing noficiation text

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinWorldCoordinates.java

partially fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15613

implement a better hashing method for WorldCoordinates

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/packets/MixinS01PacketJoinGame_FixDimensionID.java

Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13955
Feel free to come up with a better implementation of this

Add int dimension id to end of login packet

---

src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlock_LighterWater.java

Reduces water's opacity from 3 to 1 like in modern versions. This tweak is off by default.

Add lighter water tweak

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/advancedsolarpanels/MixinAdvancedSolarPanel.java

Pendant to https://github.com/GTNewHorizons/Gravitation-Suite-Neo/pull/19

Fix MT Core Recipe

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal_FixWordLeak.java

Should fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15722

Add another null check to the FixWorldLeak mixin

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinTileEntityHopper.java

Fixes https://github.com/GTNewHorizons/Hodgepodge/issues/362

Fix Hopper behaviour

---

src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinTileWandPedestal.java

It's still unclear to me as how TC4 is syncing the update to client, but this works for now

fix cv powered wand recharge pedestal not updating in MP

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinChunkProviderEndOfTime.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinWorldProviderEndOfTime.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinTileWandPedestal_VisDuplication.java

Related https://github.com/GTNewHorizons/GT5-Unofficial/pull/2633

Move some mixins (formerly ASM) from gt5u(bartworks) that makes more sense in hodgepodge

---

src/main/java/com/mitchej123/hodgepodge/asm/AsmTransformers.java
src/main/java/com/mitchej123/hodgepodge/asm/transformers/mc/SpeedupLongIntHashMapTransformer.java

Add obf mappings to HashMap transformations

---

src/main/java/com/mitchej123/hodgepodge/mixins/hooks/ModProfileResult.java
src/main/java/com/mitchej123/hodgepodge/mixins/preinit/MixinLoadController_logModTimes.java
src/main/resources/mixins.hodgepodge.json

Quick and dirty mixin to time and log event timings to a "csv" (uses semicolon)

Quick and dirty mixin to time and log event timings to a "csv"

---

build.gradle.kts
src/main/java/com/mitchej123/hodgepodge/mixins/hooks/ModProfileResult.java
src/main/java/com/mitchej123/hodgepodge/mixins/plugin/HodgepodgePreInitMixinPlugin.java
src/main/java/com/mitchej123/hodgepodge/mixins/preinit/MixinLoadController_logModTimes.java
src/main/resources/mixins.hodgepodge.json

Adds an optional mixin to log event timing to a csv

Quick and dirty mixin to time and log event timings to a "csv" (uses semicolon)

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiConfirmOpenLink.java

fix button in open link GuiScreen not being centered

---

src/main/java/com/mitchej123/hodgepodge/client/HodgepodgeClient.java
src/main/java/com/mitchej123/hodgepodge/client/handlers/ReloadSoundsGui.java
src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/resources/assets/hodgepodge/lang/en_US.lang

Add a button in the F3 menu to refresh the sounds without needing to press F3+S

Add button to refresh the sounds

---

src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinContainerFilingCabinet.java

Shadow methods and extend Container instead of doing `(ContainerFilingCabinet) (Object) this`

cleanup MixinContainerFilingCabinet

---

src/main/java/com/mitchej123/hodgepodge/hax/LongChunkCoordIntPairSet.java

context: https://discord.com/channels/181078474394566657/305737190195986433/1319312600928096368

fix stream

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinItemReed.java

Fix Sugar Cane placement on replaceable blocks

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/asm/AsmTransformers.java
src/main/java/com/mitchej123/hodgepodge/asm/transformers/mc/NBTTagCompoundHashMapTransformer.java
src/main/java/com/mitchej123/hodgepodge/asm/transformers/mc/NBTTagCompoundHashMapTransformerTransformer.java
src/main/java/com/mitchej123/hodgepodge/config/ASMConfig.java
src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/core/CoreCompat.java
src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinForgeChunkManager_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinAnvilChunkLoader_FixAllocations.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMapData_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMapStorage_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNBTTagCompound_speedup.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNBTTagCompound_stringPooler.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNBTTagList_speedup.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNBTTagString_stringPooler.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSaveHandler_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinScoreboardSaveData_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSpawnListEntry_optimizeSpawning.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSpawnerAnimals_optimizeSpawning.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinThreadedFileIOBase_noSleep.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinVillageCollection_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/NBTTagListExt.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/SafeWriteNBT.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/SpawnListEntryExt.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinMazeHandler_threadedIO.java
src/main/java/com/mitchej123/hodgepodge/util/StringPooler.java
src/main/java/com/mitchej123/hodgepodge/util/WorldDataSaver.java

* NBT Copy (micro?)optimizations
* NBT String Pooling
* Save world data on IO thread (mineshafts.dat, villages.dat, level.dat, forcedchunks.dat, etc)
* Save TC4's labyrinth.dat on the File IO thread
* Add support for Salis Arcana updating the labyrinth file format version
* Add optional backups to .dat file saving
* Add optional config to skip saving of Mineshaft.dat
* Optimize Mob Spawning
* Add another CCIP Allocation reduction
* Run FastLongInt transformer on servers as well...
* Mark WorldSavedData instances that use a safe implementation of writeNBT with SafeWriteNBT to avoid a copy, otherwise copy before sending to the IO Thread to avoid potential CMEs
* Safe implementations identified: MapData, MapStorage, ScoreboardSave, VillageCollection
* Add …

Various Optimizations

---

src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBiomeGenBase.java

11% of tick time for one CallbackReturnable is crazy

fix getFloatTemperature causing lag

---

src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockBed_AlwaysSetsSpawn.java

Backport instant bed spawn setting

---

src/main/java/com/mitchej123/hodgepodge/HodgepodgeEventHandler.java

Fix client desync with item in hand

---

dependencies.gradle
src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinCommandTime.java
src/main/resources/assets/hodgepodge/lang/en_US.lang

For when you want to know what the current world time is.

Add `/time get`

---

src/main/java/com/mitchej123/hodgepodge/HodgepodgeLateMixins.java
src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java

Converts all the mixin setup to use the new flavor which was taken from Hodgepodge itself and moved to GTNHLib.

Convert mixin setup to use GTNHLib

---

src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/shutup/MixinEntityLiving.java

For whatever reason Minecraft logs these instead of ignoring them, and it was getting *really* annoying.

Silence some "none" sounds

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerPlayClient_ItemThrower.java
src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/packets/MixinS0EPacketSpawnObject_ItemThrower.java
src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/S0EPacketSpawnObjectExt.java

Add mixins to synchonize from server to client the thrower of an item entity

---

src/main/java/com/mitchej123/hodgepodge/util/StringUtil.java

you actually don't need a new array, you can write on top of the current one
There is a test on this particular method and it's passing

Small improvements on removeFormattingCodes

---

src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinTEReactorCacheReactorSize.java

https://spark.lucko.me/h1uCxgqfDS?hl=1767

Add IC2 reactor size caching to reduce lag

---

src/main/java/com/mitchej123/hodgepodge/SimulationDistanceHelper.java

In light of the recently reported issue, I wanted to add a bit more logging.
Not sure what else could cause this issue, since I can't reproduce it currently. But a bit of logging shouldn't hurt.

Log when failing to remove tick from ticklist

---

src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java

* Add NBT speedup exclusion for fastcraft
* Add Config for IOOBE Render Distance
* Also add ArchaicFix to excluded mods

Misc compat fixes

---

src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java

Fix Last Millenium mixin mixup
