- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixIc2Nightvision/MixinIc2NanoSuitNightVision.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixIc2Nightvision/MixinIc2QuantumSuitNightVision.java
Removes a silly "feature" for such expensive armor.
> Prevents the nightvision on the NanoSuit & QuantumSuit from blinding people when it's bright out

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/dropPickedLootOnDespawn/MixinEntityLiving.java
Mobs drop the equipment they looted when being despawn.
Alternative to 'preventPickupLoot' tweak (#10).
Only picked up equipment is dropped at despawn, no additionnal drop.
> Mobs picking stuff no longer protected against despawn logic

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixUnprotectedGetBlock/vanilla/MixinVillage.java
Patching VillageCollection is not enough, a ghost chunkload can happen in Village too.
There's a [few more ghost chunkload fixes pulled into later versions of forge, if anyone wants to pull those in](https://github.com/MinecraftForge/MinecraftForge/pull/4689/commits), however this is just the one that I have had major issues with.
> Village getBlock fix

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixIc2ReactorDupe/MixinTileEntityReactorChamberElectric.java
- src/main/java/com/mitchej123/hodgepodge/mixins/hideIc2ReactorCoolantSlots/MixinTileEntityNuclearReactorElectric.java
Address https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8084 and https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/16
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8084 is fixed by hiding the coolant cell slot from automations when it's not a fluid reactor (i.e. limiting the inventory size).
https://github.com/GTNewHorizons/Dupes-Exploits-GTNH/issues/16 : IC2 is calling the wrong method to notify block updates. Correcting the call fix the problem.
> Add reactor related fixes

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixIc2Hazmat/MixinIc2Hazmat.java
Changes IC2 hazmat check to work with gt5u radiation hazmat check
Fixes the IC2 items (like plutonium, ic2 rods) giving poison when using gt5u hazmat protection
> Mixins for IC2 Hazmat

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/fixic2directinventoryaccess/item/MixinItemCropSeed.java
Allows adjustment of the max stack size of IC2 seeds from the ic2 default of 1, to hodgepodge's default of 64 (configurable).
Tested with unknown seeds, NEI cheated in seeds, seeds from crops.  Tested using the seeds, as well as the cropnlyzer.
> Allow IC2 seeds to stack

- src/main/java/com/mitchej123/hodgepodge/asm/HodgePodgeASMLoader.java
- src/main/java/com/mitchej123/hodgepodge/asm/SpeedupProgressBarTransformer.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
Every .step() function on ProgressBar calls `stripSpecialChars` because the rendering doesn't support some UNICODE.
StripSpecialChars calls `CharMatcher.anyOf(ALLOWED_CHARS)` on every invocation, which does a bunch of allocations, sorting, etc.  This wasn't a big deal on Vanilla, or other mods because they're not spamming thousands of materials on the progress bar.
The obvious solution would be just... don't call this at all, and that might be safe for English Locales... but given strings sent to the progress bar might be localized, we instead backport the behavior from later forge versions which cache a static copy of `DISALLOWED_CHAR_MATCHER` and use that, instead of creating a new one on every function call.
> Speedup Progress Bar

- src/main/java/com/mitchej123/hodgepodge/core/util/ItemStackHashingStrategy.java
Will degrade back to a linked list or a tree on collision.
Proper fix might be re-implementing ItemStackMap that fully implements the Map interface.
> Ugly fix for wildcard meta; will degrade back to a linked list or a tree on collision.

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinTileEntityHopper.java
fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7778
I think it is reasonable for `Drawer` to sync after each write operation
And `Hopper` needs to use 2 write operations on `Drawers` to finish transferring items, which is not reasonable
So I tried to fix it with `mixin` and it seems to be working
https://user-images.githubusercontent.com/49554020/162173928-439ffd36-7a61-4a21-ae67-c379fc7707e8.mp4
> Fix Drawer + Hopper voiding items

- dependencies.gradle
- repositories.gradle
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/mrtjpcore/MixinFXEngine.java
This fixes an annoying issue which causes the hotbar to darken when the player switches to third person mode. I believe the root cause is that lighting is re-enabled in RenderWorldLastEvent by MrTJPCore, when the HUD renderer expects it to be disabled. The workaround is to keep lighting disabled, which is what is done here.
Can someone confirm that they see the issue without the fix applied?
Before:
After:
Offending code in MrTJPCore: https://github.com/MrTJP/MrTJPCore/blob/adbfa1fe6eff596250949ff13ee3195218db3292/src/mrtjp/core/fx/FXEngine.scala#L140-L144
> Fix hotbar turning dark in third-person when Project Red is installed

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinWorldServerUpdateEntities.java
Attempts to fix <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6976>
To avoid causing too much lag (I doubt that would actually be the case, but vanilla probably doesn't call updateEntities for this reason), the updates in worlds without players are throttled to run only every 200t (10s)
> Fix world entity leak

- src/main/java/com/mitchej123/hodgepodge/asm/PollutionClassTransformer.java
Fix GTNewHorizons/GT-New-Horizons-Modpack#8955 , may be GTNewHorizons/GT-New-Horizons-Modpack#10159 and whatever depends on what Hodgepodge was supposed to patch but was silently removed from active transformers following the exception...
> Class names are deobfuscated

- src/main/java/com/mitchej123/hodgepodge/client/ClientTicker.java
- src/main/java/com/mitchej123/hodgepodge/client/DebugScreenHandler.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgePodgeClient.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- Java version, vendor and 32bit/64bit
- GPU name
- OpenGL version
- CPU cores
- OS name, version and architecture
CPU name/vendor info is very difficult to get. MC uses the `oshi-core` library in the newest version(s?). If someone knows if one of the libraries included in 1.7.10 is able to do this (or something similar) too, please let me know and I'll add it too.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10241
> Add more Hardware Info to F3 Overlay

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinRendererLivingEntity.java
- src/main/java/com/mitchej123/hodgepodge/mixins/projecte/MixinObjHandler.java
This adds two fixes.
MC-10135 causes the world to render with incorrect lighting in third person after you get shot by a skeleton and has a fairly straightforward fix. I've used a simple fix I made for this in 1.12 without problems, so I'm backporting it to 1.7 here. I deliberately left the config name generic as I have a few more 1.12 fixes for similar issues that could potentially be applied here later.
ProjectE is currently incompatible with the smelting list replacement since it assumes the returned map is a HashMap.
```
[08:51:20] [Client thread/ERROR] [FML]: Caught exception from ProjectE
java.lang.ClassCastException: com.mitchej123.hodgepodge.core.util.ItemStackMap cannot be cast to java.util.HashMap
at moze_intel.projecte.gameObjs.ObjHandler.registerPhiloStoneSmelting(ObjHandler.ja …
```
> Miscellaneous fixes

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/mrtjpcore/MixinPlacementLib.java
This is an alternative solution to https://github.com/GTNewHorizons/ProjectRed/pull/17 that patches `PlacementLib` directly. It has the advantage of fixing any other code/mods that might depend on `PlacementLib`.
> Add PlacementLib patch for components popping off chunks

- src/main/java/com/mitchej123/hodgepodge/asm/InventoryEffectRendererTransformer.java
- src/main/java/com/mitchej123/hodgepodge/asm/PollutionClassTransformer.java
- src/main/java/com/mitchej123/hodgepodge/asm/util/AbstractClassTransformer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft.java
Mere injection of hooks usually does not require COMPUTE_FRAMES. This makes the pollution class a little bit more mixin/asm friendly.
> Do not use COMPUTE_FRAMES literally everywhere

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/textures/client/MixinRenderItem.java
Mark any icon that gets rendered for an animation update, this method can be called by other mods to render their internally stored IIcon so we make sure we mark those for an update.
> RenderItem mixin

- src/main/java/com/mitchej123/hodgepodge/client/DebugScreenHandler.java
Since a lot of mods add custom info to the left side it becomes a mess quickly, and it doesn't look nice at there.
> Move animationsMode debug info to the right

- src/main/java/com/mitchej123/hodgepodge/asm/HodgePodgeASMLoader.java
- src/main/java/com/mitchej123/hodgepodge/asm/InventoryEffectRendererTransformer.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
this was already fixed before but it made the potion effect render with a shadow when NEI was hidden, so I changed it to make it render in the foreground when NEI is hidden and in the background if NEI is open
> Fix vanilla potion effects rendering above the NEI tooltips in the inventory

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft_ResizableFullscreen.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft_UnfocusedFullscreen.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinMinecraft_fixFullscreenResizable.java
fix the vanilla 1.7.10 bug that makes your game exit fullscreen when the game looses focus (if you use alt tab)
tested and working in full pack
> Fix fullscreen when tabing out

- src/main/java/com/mitchej123/hodgepodge/client/DebugScreenHandler.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgePodgeClient.java
- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/core/handlers/ClientKeyListener.java
- src/main/java/com/mitchej123/hodgepodge/core/util/ManagedEnum.java
- src/main/java/com/mitchej123/hodgepodge/core/util/RenderDebugHelper.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinRenderGlobal.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/textures/client/MixinTextureMap.java
This will send a chat error message when a TESR is breaking render states. Detail will be routed to logs instead for not clobbing up the entire chat menu. I didn't log the diff in value, just merely logged which got changed, because it should be pretty obvious on the cause of glitches when we know who is at fault.
currently only available for TESRs. Can be implemented for other stuff e.g. items, entities or blocks as well.
> implement an opt-in render debug mode

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinRenderManager.java
> fixDebugBoundingBox being offset up for the player

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityFireball.java
fix the vanilla bug that doesn't save the firecharge's acceleration to the NBT causing the fire charge to stay immobile on world/chunk reload
> fix fireballs that stay immobile on world/chunk reload

- src/main/java/com/mitchej123/hodgepodge/core/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinNetHandlePlayClient.java
before
after
https://user-images.githubusercontent.com/39122497/188915079-bedea597-242f-4f00-9443-88d18c7df71e.mp4
About printChatMessageWithOptionalDeletion second argument:
"0" will not delete any duplicated chat, "1" is occupied by vanilla, "2" is occupied by Forge, so I use 3
> Stop "You can only sleep at night" message filling the chat

- src/main/java/com/mitchej123/hodgepodge/Common.java
- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/asm/BibliocraftTransformer.java
- src/main/java/com/mitchej123/hodgepodge/asm/HodgePodgeASMLoader.java
- src/main/java/com/mitchej123/hodgepodge/asm/ThermosFurnaceSledgeHammer.java
- src/main/java/com/mitchej123/hodgepodge/asm/transformers/tconstruct/TabRegistryTransformer.java
- src/main/java/com/mitchej123/hodgepodge/client/DebugScreenHandler.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgePodgeClient.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeMixinPlugin.java
- src/main/java/com/mitchej123/hodgepodge/core/handlers/ClientKeyListener.java
- src/main/java/com/mitchej123/hodgepodge/core/util/AnchorAlarm.java
- src/main/java/com/mitchej123/hodgepodge/core/util/BlockMatcher.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/hungeroverhaul/MixinHungerOverhaulLowStatEffect.java
- src/main/java/com/mitchej123/hodgepodge/mixins/ic2/MixinItemCropSeed.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEffectRenderer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinEntityPlayer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinFurnaceRecipes.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinRandomPositionGenerator.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinS02PacketChat.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/MixinWorldGetBlock.java
- src/main/java/com/mitchej123/hodgepodge/mixins/minecraft/server/MixinHttpUtil.java
The HodgePodgeASMLoader makes references to the LoadingConfig instance inside the Hodgepodge class.
This unfortunately causes cascading classloading, because the Hodgepodge class also refers to classes in minecraft/forge code that shouldn't be loaded this early (for instance, the arguments of the event handlers). This cascading classloading can cause the infamous MixinTargetAlreadyLoadedException crash.
This PR fixes this cascading classloading by migrating the `log`, `config`, `thermosTained`, and `RNG` fields from the Hodgepodge class to a new utility class specifically designed to prevent the previously mentioned cascade.
> Fix ASM transformer causing cascading classloading

- src/main/java/com/mitchej123/hodgepodge/client/biomesoplenty/BOPFogHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/biomesoplenty/AccessorFogHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/biomesoplenty/MixinFogHandler.java
When using GasStation, `speedupBOPFogHandling` produces a very similar crash to #72. This happens because GasStation doesn't handle inner mixin classes correctly. (https://github.com/FalsePattern/GasStation/issues/3)
This gave me the idea to refactor the mixin to not use an inner class, and instead move its implementation into a helper class. This fixes the crash, and the crash with BetterFPS as well.
I verified that the mixin still works. `EntityRenderer#setupFog` takes up 4.7% of CPU time when it's disabled, which goes down to 0.1% when it's enabled.
> Fix `speedupBOPFogHandling` incompatibility

- build.gradle
- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinTileEntityFurnacePollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinTimeCommandGalacticraftFix.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldUpdateEntities.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/bibliocraft/MixinBibliocraftPatchPacketExploits.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/galacticraftcore/MixinGalacticraftRocketPollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2IronFurnacePollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/minecraft/MixinExplosionPollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/railcraft/MixinRailcraftBoilerPollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/railcraft/MixinRailcraftCokeOvenPollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/railcraft/MixinRailcraftTunnelBorePollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinThaumcraftAlchemyFurnacePollution.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ztones/MixinZtonesPatchPacketExploits.java
- src/main/java/com/mitchej123/hodgepodge/util/PollutionHelper.java
- src/main/resources/mcmod.info
Adaption of https://github.com/MinecraftForge/MinecraftForge/commit/638a54b04ab896fd18bdc5da48269f5465e5b61c
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9147 when fastcraft is not in use
Note: Targeting 2.0 branch, will rebase to master if merged after 2.0 branch
> Faster tileentity removal for World.updateEntities

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinItemSoup.java
GTNH [increases](https://github.com/GTNewHorizons/GT5-Unofficial/pull/952) mushroom stew stack size, however the vanilla method for eating stew just throws the whole stack away.
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9908
I know this is a minuscule fix in the grand scheme of things, though this is my first time using mixins and I prefer starting small.
> Vanilla fix: Don't delete whole stack when eating mushroom stew

- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinInventoryEffectRenderer_PotionEffectRendering.java
Removes dependency on NEI (and by extension, CCC and CCL).
Also makes the potion effects only get dimmed when there are actually widgets being drawn in the left panel. Previously they were dimmed even if the bookmark panel was hidden, or if NEI was disabled in the settings but not hidden. Now the fix works as intended both with NHEI and upstream NEI.
> Fix `fixPotionEffectRender` crashing without NEI, and make it work as intended

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSoundHandler.java
This fixes a bug in vanilla Minecraft where certain player sounds were registered as animal(AKA friendly creatures) sounds. This caused them to not be played when the friendly creatures sounds were muted.
GTNH Issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11752
Here's a link to the Mojang bug report: https://bugs.mojang.com/browse/MC-36360
The issue has since been fixed in Vanilla minecraft so this is a backport of sorts. The problem is that in the vanilla `sounds.json` file these sounds are registered incorrectly, however you are unable to override this setting via resourcepacks, so a mixin is needed to intercept the sounds loading in, and dynamically change the SoundCategory depending on the name of the sound.
> Vanilla Fix: Player Sound Registered as Friendly Creatures

- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/util/PollutionHelper.java
Using a furnace causes a crash when pollution is enabled in the config (which it is by default!) while GT5 is not present.
This PR fixes this by adding a check that GT5 is present before using GT's pollution API.
> Check for GT5's presence before using GT_Pollution

- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIc2Hazmat.java
Currently the game crashes if `fixIc2Hazmat` is enabled while IC2 is present without GT5. This is because the mixin is initialized in the early phase before non-coremods have been discovered, causing the `TargetedMod.GT5U` check to always succeed.
This PR moves the mixin to the late phase as a solution. However, this alone would still cause the mod to crash when IC2 and GT6 are both present, since GT6 has the same modid as GT5. For this reason, I also added a check that the GT mod in question has GT5's version.
> Only apply IC2 hazmat mixin if GT5 is present

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/journeymap/MixinWorldData.java
should fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11876
I didn't test it since I don't have any servers to join but it injects properly and should fix the link issue
> Prevents journeymap from using illegal character in file paths

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiScreenResourcePacks.java
there is a forge bug where if you have a space character on your folder path with Windows, when you click the "open resource pack folder" button it will not work. This PR fixes it
> fix resource pack folder sometimes not opening on windows

- src/main/java/com/mitchej123/hodgepodge/mixins/late/ztones/MixinZtonesPatchPacketExploits.java
here while the method name doesn't need remaping the name of the targeted MethodeNode needs remapping
> fix remaping issue in MixinZtonesPatchPacketExploits

- build.gradle
- gradle.properties
- repositories.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/journeymap/MixinWaypointManager.java
Under LWJGL3 the bug in the original code was triggered because the scroll amounts can reach low values like 1/-1, lwjgl2 reports huge numbers (>120 on Windows, >10 on Linux) so the reversed clamping seemingly always worked. LWJGL3 reports properly scaled scroll amounts, so I disable the clamping if it's detected for a better user experience.
> Fix journeymap scrolling

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGameSetttings.java
by default in vanilla minecraft it is under the gameplay category instead of movement
> Moves the sprint keybind to the movement category

- dependencies.gradle
Modify the `dependencies.gradle` mod dependencies to only be present at this mod's compile and runtime classpaths, without being published to maven. This way Hodgepodge can be added to the dev environment of any mod without pulling in all its optional dependencies.
There's no other way I'm aware of doing it in current gradle versions other than manually adding a new configuration (dependency set) and extending the internal gradle classpath ones from it.
> Don't publish transformed mod dependencies in maven metadata

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiTextField.java
Added mixin that allows Copy / Select / Insert text using Command key on MacOS.
This works in pretty much inputs that using GuiTextField component (NEI, Chat, Server IP insertion and many others)
It's very awful to me and i think other mac users to use control.
It works on command only i think in 1.8+ minecraft, but i didn't remove control shortcut for now and i don't think it needs.
Works in GTNH too.
> Fix Minecraft Not Supporting MacOS CMD Shortcuts in Text Fields

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
because the method public String[] getASMTransformerClass() gets called twice by FML
> Stop saying twice in log which ASM transformers it's loading

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/xaeroworldmap/MixinGuiMap.java
Xaero's World Map tries to clamp scroll wheel values by dividing by 120. This does not work with LWJGL 3 since it reports sane scroll wheel values, unlike LWJGL 2.
This makes it use the raw scroll wheel value instead if lwjgl3ify is detected, which makes scrolling work as expected.
Fixes the "unrelated note" in #172
> Fix scrolling Xaero's World Map with LWJGL 3

- src/main/java/com/mitchej123/hodgepodge/client/handlers/ClientKeyListener.java
So many people mistype shift+d given it's sneak move right. Not so many people would press ctrl+shift+d though.
> make all debug keybinds require simultaneous ctrl and shift instead of just shift

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinTextureAtlasSprite.java
Context: https://discord.com/channels/181078474394566657/603348502637969419/1088778698326560809
> fix weird NPE introduced by #202

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/minechem/MixinPotionInjector.java
Similar fix to #192
Includes a config option as well to set the ID since that wasn't possible originally
> Minechem Java 12 compat: Stop potion array expansion and add config for potion ID

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/textures/client/MixinTextureMap.java
Add a priority to the TextureMap mixin to fix crash on startup with TEXTURE_OPTIMIZATIONS from falsetweaks.
I don't know if its a proper fix.But its work on my 800+ mods modpack.
> Add a priority to the TextureMap mixin

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIc2QuantumSuitHoverMode.java
I don't think there's any issues open for this or anything, but I made a quantum chestplate today and the hover mode on it makes you slowly float down, which sucks ass compared to the advanced nano chestplate. Given the latter is used in the recipe for the former, to me it seems like that should mean it can at least do everything the old one can. I don't know if this is officially considered a bug but it seems like some ic2 "balance" that nobody would miss, in the same vein as the stock ic2 night vision blinding you in the sun. 
Also if I have to go back to the advanced nano chestplate until gravisuit at ZPM my outfit will no longer match
> Fix Quantumsuit hover mode slowly losing altitude

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinFontRenderer.java
LLibrary uses an [access transformer](https://github.com/iLexiconn/LLibrary/blob/1.7.10/src/main/resources/META-INF/llibrary_at.cfg) which increases the visibility of `FontRenderer` methods to `public` which clashes with the package-private visibility of `MixinFontRenderer.wrapFormattedStringToWidth`:
```
Mixin Errors in Stacktrace: 
net.minecraft.client.gui.FontRenderer:
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PACKAGE @Overwrite method func_78280_d in mixins.hodgepodge.early.json:minecraft.MixinFontRenderer from mod hodgepodge cannot reduce visibiliy of PUBLIC target method
Mixins in Stacktrace: 
net.minecraft.client.Minecraft:
mixins.hodgepodge.early.json:minecraft.MixinMinecraft_UnfocusedFullscreen from mod hodgepodge …
```
> Fix LLibrary incompatibility

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinOpenGuiHandler.java
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13125
and possibly fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11950
before this fix, OpenGuiHandler would always set windowId on the player's openContainer after calling player.openGui.
This is a problem since many mods like Forestry, SpiceOfLife and AdventureBackpacks2 can possibly return null in their getLocalGuiContainer(). openGui and OpenGuiHandler don't check if the result of that was null, and so windowId gets set on the wrong openContainer. This bypasses the windowId validity check in S30WindowItems packet which can crash the client when assigning itemStacks to the wrong container.
After the fix, player.openGui() logic and getLocalGuiContainer() result check happen inside …
> Fix crashes when opening forestry/adventure backpacks and quickly switching selected item

- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/client/HodgepodgeClient.java
- src/main/java/com/mitchej123/hodgepodge/client/PollutionTooltip.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/galacticraftcore/MixinGalacticraftRocketPollution.java
- src/main/java/com/mitchej123/hodgepodge/util/PollutionHelper.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12957
Restore pollution tooltips that were previously added through ModMixins.
> Add pollution tooltips

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinContainer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerPlayClient_FixHandleSetSlot.java
The exact same bug keeps popping up over and over again
Here's just some recent examples:
https://github.com/GTNewHorizons/NotEnoughItems/issues/388
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12658
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13125
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11950
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10933
And it's no wonder, since any time there's a mismatch between server/client open container size = potential crash
This is such an easy way for a mod to shoot itself in the foot especially when trying to deal with any sort of complex or dynamic gui container. The solution is a simple sanity check in handling the 2 offending server packets, so the problem is solved at …
> Fix crashing due to server/client container size mismatch

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerLoginServer_OfflineMode.java
[Discord Discussion](https://discord.com/channels/181078474394566657/401118216228831252/1118794386432589834)
The error message could be better and more vague.
Test results:
tested with GTNH 2.3.3 server (docker container) with online_mode set to false
With no fix:
* Online client -> offline server: Not whitelisted error
* Offline client (same name as online) -> offline server: Not whitelisted error
* Offline client (different name as online) -> offline server: Not whitelisted error
With fix:
* Online client -> offline server: Connected (uuid mapped)
* Offline client (same name as online) -> offline server: Connected (uuid mapped)
* Offline client (different name as online) -> offline server: Not in cache error
whitelist errors were due to uuid not being mapped
> Add offline mode UUID mapping

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/lotr/MixinLOTRRecipes.java
Atm lotr itself doesn't have j12+ support so I left it at transformedModCompileOnly for now. I have patches ready in [my own mod](https://github.com/mist475/MistLotrTweaks) that I will pr some time later.
> Fix lotr error with speedupVanillaFurnace

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/bibliocraft/MixinPathSanitization.java
- src/main/java/com/mitchej123/hodgepodge/util/PathSanitizer.java
Creating books with slashes in the title and saving them via the typesetting table could cause exceptions and crashes.
> Fix path handling of bibliocraft saved books to replace invalid characters with dashes

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRenderGlobal.java
Fixed this pullrequest [here](https://github.com/GTNewHorizons/Hodgepodge/pull/235) that make tile entities invisible
Same ammount of ceramic jar from zelda mod
before
https://cdn.discordapp.com/attachments/1022680913122951258/1142524047641546852/Capture_decran_2023-08-19_20-20-52.png 
After
https://cdn.discordapp.com/attachments/1022680913122951258/1142524047322792036/Capture_decran_2023-08-19_20-21-32.png
note : like i am thinking that the other mixin optimize more performance but not , he disabling tile entities renderer XD
So now its just a micro optimization
> Micro reduce fps lags with tileentities

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinAbstractClientPlayer.java
`AbstractClientPlayer#getDownloadImageSkin` depends on the now-defunct skins.minecraft.net, breaking skin loading for (at least) FTBU and BQ.
This redirects it to a working public api that can accept usernames. Should this be changed to use a different api setup (currently it is not the fastest, due to performing uuid lookup), or is this good enough?
> Fix player skin fetching method in AbstractClientPlayer

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinElectricItemManager.java
Follow-up to https://github.com/GTNewHorizons/Hodgepodge/pull/230
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14357
> Fix another lag caused by IC2 spamming detectAndSendChanges

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiContainerCreative.java
> Remove all items from the creative search tab to prevent lag/crash

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/client/chat/ChatComponentCount.java
- src/main/java/com/mitchej123/hodgepodge/client/chat/ChatHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
Compacts identical consecutive chat messages together
~~Also disabled by default the message "You can only sleep at night" rendering above the hotbar~~
> Compact chat

- src/main/java/com/mitchej123/hodgepodge/common/KeyBindingDuck.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_UpdateKeys.java
this way if you have your walk forward button pressed when you close your inventory, it directly starts walking, you don't have to unpress the key and press it again
> check all key states when you close an inventory to press the keybinds

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinGuiIngameForge_CrosshairInvertColors.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinGuiIngameForge_CrosshairThirdPerson.java
Stop inverting the colors of the crosshair
default : 
Not inverted :
This will conflict with https://github.com/GTNewHorizons/Hodgepodge/pull/247 without saying that is has merge conflicts
> Don't invert crosshair colors

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
fix https://github.com/GTNewHorizons/Hodgepodge/issues/251
It would crash for chat messages added with the vanilla printChatMessageWithOptionalDeletion since the message would already be deleted from the chat by vanilla.
You can test it with the command `/travellersgear` and then `space` and then spam tabcompletion
> Fix compact chat crash

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
Context: https://discord.com/channels/181078474394566657/603348502637969419/1157978680946085929
> Add config for fixNetHandlerLoginServerOfflineMode

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockGrass.java
- Prevent chunk loading
- Avoid doing any work on blocks that can't turn to grass, meaning the block itself and the block directly below
- Remove duplicate `World#getBlockLightValue` call
- Remove unused `World#getBlock` call with unused result
> Add performance optimizations for grass block random ticking

- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinEntityReflection.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinExtendedPlayer.java
Allow `getDownloadImageSkin()` fixes to apply to Witchery's Mirror content (demon reflections, player camouflage and sleeping bodies).
See issue in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13903
This wasn't fixed before by solutions such as https://github.com/GTNewHorizons/Hodgepodge/pull/237 primarily due to Witchery's decision to duplicate the vanilla method rather than referencing it.
> Fix Witchery's Mirror Reflections

- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinOpenGuiHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinContainer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityLivingBase_FixPotionException.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityPlayer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinFontRenderer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinFurnaceRecipes.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiContainerCreative.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_CompactChat.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGuiNewChat_FixColorWrapping.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinInventoryEffectRenderer_FixPotionEffectNumerals.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinItemPotion_FixRomanNumerals.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorld_FixLightUpdateLag.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/biomesoplenty/MixinBOPBiomes.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/hungeroverhaul/MixinHungerOverhaulModuleHarvestCraft.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/journeymap/MixinWaypointManager.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/projecte/MixinObjHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinEntityGolemBase.java
> Small Cleanup (mostly `@Share` / `@Local`)

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extratic/MixinRecipeHandler.java
Disabled additional ExtraTiC's Metallurgy 3 Precious Module that were still creating conflicts.
Specifically M3Precious recipes and alloy mixing,
> ExtraTiC Patch p.2

- src/main/java/com/mitchej123/hodgepodge/mixins/late/bibliocraft/MixinBibliocraftPatchPacketExploits.java
Changes:
- Don't kick players from their singleplayer world
- Make exceptions for empty maps in addition to the original filled maps
Fixes https://github.com/GTNewHorizons/Hodgepodge/issues/225 for real
> Update Packet Exploit Patch for Bibliocraft

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinKeyBinding.java
Fixes the error I was seeing with lwjglxdebug
```
Description : Invalid key -1
Stacktrace  :
org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43)
org.lwjgl.system.JNI.invokePI(Native Method)
org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3746)
org.lwjglx.debug.$Proxy$4840.glfwGetKey577(Unknown Source)
org.lwjglx.input.Keyboard.isKeyDown(Keyboard.java:263)
net.minecraft.client.settings.KeyBinding.hodgepodge$updateKeyStates(KeyBinding.java:590)
net.minecraft.client.Minecraft.handler$zeb000$hodgepodge$updateKeysStates(Minecraft.java:6596)
net.minecraft.client.Minecraft.setIngameFocus(Minecraft.java:1386)
net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:871)
net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:119)
```
> Check for >0 instead of !=0

- build.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMessageDeserializer2.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMessageSerializer2.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinPacketBuffer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/packets/MixinS3FPacketCustomPayload_LengthLimit.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/packets/MixinS3FPacketCustomPayload_Validation.java
- src/main/java/com/mitchej123/hodgepodge/util/PacketSerializationHelper.java
This adds configurable size limits for the network packet sizes and decoded NBT sizes, and bumps the vanilla limits from 2MB to 256MB.
> Adjustable network nbt and packet size limits

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/LoadingConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thermaldynamics/MixinSimulatedInv.java
Adds checks to prevent `NegativeArraySizeException` with Thermal Dynamics upon transferring items into invalid inventories.
Where it would previously be stuck on a crashing loop with mods like Nuclearcraft, now it will simply cancels that operation.
> Thermal Dynamics NASE Prevention

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinMinecraftForge.java
Fixes [these](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/common/MinecraftForge.java#L115-L118) class names, which contain `,` instead of `.`.
> Fix Class Name Typo in Forge

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldUpdateEntities.java
Makes `fasterRemoveAll` apply to regular entities alongside tile entities by making the mixin slightly more generic.
> Apply fasterRemoveAll to Entities too

- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/voxelmap/cache/MixinCachedRegion$1.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/voxelmap/cache/MixinCachedRegion.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/voxelmap/cache/MixinComparisonCachedRegion.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/voxelmap/chunk/MixinCachedRegion.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/voxelmap/chunk/MixinComparisonCachedRegion.java
- src/main/java/com/mitchej123/hodgepodge/util/NBTTagCompoundConcurrentModificationException.java
- src/main/java/com/mitchej123/hodgepodge/util/VoxelMapCacheMover.java
VoxelMap caches the map in ZIP files in `./mods/VoxelMods/voxelMap/cache/`. However, TechnicLauncher recursively deletes all mod files in the `./mods/` directory, which [includes `.zip` files](https://github.com/TechnicPack/LauncherV3/blob/master/src/main/java/net/technicpack/minecraftcore/install/tasks/CleanupAndExtractModpackTask.java#L126).
Previously, the cache had to be backed up before doing any update, otherwise everything except the waypoints would be lost. With this PR, the file extension will be changed to `.data`. All existing files will be renamed.
> Change File Extension of VoxelMap Cache Files

- addon.gradle
- build.gradle
- build.gradle.kts
- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/asm/EarlyConfig.java
- src/main/java/com/mitchej123/hodgepodge/asm/hooks/early/EarlyASMCallHooks.java
- src/main/java/com/mitchej123/hodgepodge/asm/transformers/early/EarlyClassTransformer.java
- src/main/java/com/mitchej123/hodgepodge/rfb/ForgeConfigurationTransformer.java
- src/main/java/com/mitchej123/hodgepodge/rfb/HodgepodgeRfbPlugin.java
- src/main/resources/META-INF/rfb-plugin/hodgepodge.properties
Using an RFB plugin (lwjgl3ify required, otherwise this PR does nothing) this transforms Forge's Configuration classes to use less memory by:
- assigning constant strings to common values directly
- deduplicating other strings using Java's builtin interner
- deduplicating empty arrays to a single instance
- replacing TreeMaps for properties with fastutil's openhashmap - the ordering of the treemap does not matter for the configuration code so this is safe (unless someone does something weird to it via reflection)
Overall in the full pack these changes reduce Configuration memory usage by 45%: 271 MB to 149 MB.
> Fix egregious memory usage of Forge's Configuration class

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinBlockMagicalLeaves.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinBlockMagicalLog.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16092. Should be tested with https://github.com/GTNewHorizons/Random-Things/pull/6
> Fix Thaumcraft leaves lag

- src/main/java/com/mitchej123/hodgepodge/asm/hooks/early/EarlyASMCallHooks.java
- src/main/java/com/mitchej123/hodgepodge/rfb/ForgeConfigurationTransformer.java
Sort the config keys before saving to preserve the old configuration property order when no custom order is specified by the mod.
Closes #364
> Fix wrong config entry order after the optimizations in #357

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunk.java
Should help diagnose this crash:
```
java.lang.ArrayIndexOutOfBoundsException: Index -16 out of bounds for length 4096
at RFB-Launch//net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:1093)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_76628_c(Chunk.java:548)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:878)
at RFB-Launch//net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:862)
at RFB-Launch//net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:500)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
at RFB-Launch//net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
at …
```
> Check TE coordinates early and provide a meaningful error message if they're wrong

- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
should help with weird concurrency issues, e.g. too few processors that causes starvation, too many processors causing too much contention
> add a CPU count crash callable

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinBlockCircle.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinEntityWitchHunter.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinRiteClimateChange.java
Detect `isThundering()` based on the world info rather than the frequency of thunders of said world.
This ensures that witchery can detect storm even when weather mods modify thunder frequencies during storms.
This fixes rituals that can only be used during storms and Witch Hunter spawning.
__Example of known mods that break Witchery's storm detection:__
- [Better Rain](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2134067-better-rain-v0-15-bug-fixes)
- [Dynamic Surrounding](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings/)
> Witchery - Enhanced Compatibility Thunder detection

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinFullBrightMicroMaterial.java
This adds a mixin to fix the rendering of Lapis Caelestis microblocks. The core issue is that it passes an invalid brightness value, which causes the game to not render them, or render them as pitch black (with Angelica). ~~The mixin uses Overwrite instead of other options since the contents of the method is already changed by CCC to use the updated api (specifically to change `CCRenderState.setBrightness(16711935)` to `CCRenderState.setBrightnessStatic(16711935)`)~~. The mixin now uses ModifyConstant instead, to change 16711935 (0xFF00FF) to 240, which is the same brightness value the full blocks pass to the tesselator.
This fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12436
> Fix Lapis Caelestis Microblocks rendering

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/biomesoplenty/MixinDisableQuicksandGeneration.java
This adds a (default off) mixin to disable BOP quicksand from generating. There might be better ways to do this, but this way should be compatible with addons etc.
> Add mixin to disable BOP quicksand from generating

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSoundManager.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSoundManagerLibraryLoader.java
Minecraft has linear volume scaling so "turn volume to 50%" is not "I can hear 2x quieter".
I have to scale block sound all the way down to like 5% to hear not too loud sound in GTNH.
This PR tries to fix that.
It is exactly what https://modrinth.com/mod/logarithmic-volume-control does but better implementation
It fixes https://bugs.mojang.com/browse/MC-141201
Tested in full pack.
This does not change the max volume.
> Better volume scaling

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSoundManager.java
I thought getNormalizedVolume only affects category volume, but it actually affects individual sound.
So some sounds were affected by the new calculation twice, making them much quieter.
This PR makes mixin only applies to set category volume.
Hopefully it fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16442
> Fix sound imbalance

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinRegionFile.java
Add information about which region file has the oversized chunk(s), to make finding them easier.
> Print which file the oversized chunk is located in

- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunk.java
Adds a config option to destroy broken TEs from the world instead of crashing. This is off by default, because it can cause data loss in worlds instead of just stopping it while loading which allows for manual data recovery.
Also now logs the NBT of the offending TE to provide even more information.
> Add an option to destroy TileEntities with illegal coordinates instead of crashing

- gradle.properties
- src/main/java/com/mitchej123/hodgepodge/client/chat/ChatHandler.java
- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunkProviderClient_RemoveChunkListing.java
- src/main/java/com/mitchej123/hodgepodge/util/FastUtilLongHashMap.java
Speeds up ClientChunkProvider by removing a list duplicating everything in the map because they wanted to be able to iterate over it, and decided this was better than implementing a values iterator on the map...
```java
/**
* This may have been intended to be an iterable version of all currently loaded chunks (MultiplayerChunkCache),
* with identical contents to chunkMapping's values. However it is never actually added to.
*/
private List chunkListing = new ArrayList();
```
> Faster client chunk provider

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_FixDuplicateSounds.java
Been bugging me lately.
There is a bug where if you open a gui after a sound plays and when you close it, it will replay from the start.
> Fix duplicate sounds when closing a gui while one was playing

- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/client/handlers/ClientKeyListener.java
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinMinecraft_FastBlockPlacing.java
- src/main/java/com/mitchej123/hodgepodge/net/MessageConfigSync.java
Allow the server to block players from using the fast block placement feature.
Also blocks any clients from running older versions of hodgepodge to ensure the feature is respected. This should be kept in mind when updating the official servers.
Clients running this version can still join server without this feature
When merged this should be released as version 2.5.36
> server side control logic for fast block placing

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/candycraft/MixinBlockSugar.java
The sugar block correctly checks if the equipped item is null in the first part of it's if statement but doesn't return, this then causes an npe when it calls `player.getCurrentEquippedItem().getItem()` later.
It was reported here https://github.com/GTNewHorizons/Backhand/issues/19 but also happens without backhand installed.
Closes https://github.com/GTNewHorizons/Hodgepodge/issues/403
> Fix npe when interacting with candycraft sugar block

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockBed.java
Fixes an issue with Backhand
```java
java.lang.ClassCastException: class xonin.backhand.client.world.ClientFakePlayer cannot be cast to class net.minecraft.entity.player.EntityPlayerMP (xonin.backhand.client.world.ClientFakePlayer and net.minecraft.entity.player.EntityPlayerMP are in unnamed module of loader 'Launch' @2b4bac49)
at Launch//net.minecraft.block.BlockBed.redirect$bcf000$hodgepodge$sendMessageAboveHotbar(SourceFile:525)
at Launch//net.minecraft.block.BlockBed.func_149727_a(SourceFile:107)
at Launch//xonin.backhand.client.world.ClientFakePlayer.simulateBlockInteraction(ClientFakePlayer.java:85)
```
> Check for fake players before sending hotbar message

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinClientCommandHandler_CommandFix.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinCommandHandler_CommandFix.java
Bugs fixed :
- Forge's command handler doesn't check for a `/` at the start of a message before trying to run a command, so if you just type in the chat `commandname` it will actually run the command instead of sending a chat message
- tHe cOMmAnD HaNdLeR DoeSN'T SuPPoRt CoMManDs WriTtEN iN aNy CaSe
> Bug fix : slash command + case command fix

- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinWorldProviderEndOfTime.java
If it's raining in the Overworld and you enter The Last Millenium, it will still be raining, so fixes this.
The code is copied from Personal Space.
https://github.com/GTNewHorizons/PersonalSpace/blob/d26f154f327bac6ac55f8e08214363cf39d9ce0f/src/main/java/me/eigenraven/personalspace/world/PersonalWorldProvider.java#L197
> Disables weather completely on The Last Millenium

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/xaerominimap/MixinMinimapRenderer.java
Xaero's minimap has three way of showing the player location either as a crosshair, dot or arrow. The dot only checks if the crosshair is not active which means you end up with the following while arrow is chosen
When the minimap is `lockedNorth` it also forces you to use the arrow which again causes the dot to render.
> Fix Xaero's minimap player entity dot rendering while disabled

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerLoginServer_OfflineMode.java
Reworks the offline handler to default to the old way if user is not found in cache to better support proxies
> Rework offline handler - Proxy support

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldServer_LimitUpdateRecursion.java
Some configurations of water and lava can cause infinite recursive block update loops (this seems to be a vanilla bug), this is not a full fix but it at least stops crashes from happening and replaces them with logging.
Tested by setting the limit to a very low value in dev and observing suppressed block updates during worldgen.
> Limit recursive block updates to prevent stack overflow crashes

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/cofhcore/MixinOreDictionaryArbiter.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGameSettings_FixArrayOutOfBounds.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinItemWispEssence_Both.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinItemWispEssence_Client.java
The keyboard fix in gt++ was 600 lines of broken ASM combined with reflection when it could be a 5 lines mixin 
Transfered the thaumcraft ItemWispEssence fix
Transfered the cofh npe fix
See : https://github.com/GTNewHorizons/GT5-Unofficial/pull/3238
> Transfer GT++ ASM fixes to mixins in hodgepodge

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinIC2TileEntityCrop.java
Each IC2 plant can implement a `onEntityCollision` behavior for when it should be trampled.  
By default, crops can be trampled by sprinting over it.
When an IC2 crop is trampled this way, it will set the block below it to dirt.
This is an issue, because it means that even farmland which shouldn't be tramplable (at least via the vanilla falling-onto-farmland mechanic) like Fertilized Dirt can be trampled and will be replaced with *normal dirt* (instead of the un-tilled fertilized dirt).
This fix just disables the ic2 crop trampling by sprinting for blocks that aren't normal farmland.
If there are any custom farmlands that should be able to be trampled, they can just be specially cased in the fix, but I'm not aware of any.
*Could* also be implemented by calling `onFallenUpon` when …
> fix ic2 crops making any farmland trampleable

- src/main/java/com/mitchej123/hodgepodge/config/ASMConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/PollutionConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/PollutionRecolorConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/gui/HodgepodgeGuiConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/gui/HodgepodgeGuiConfigFactory.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/fml/MixinGuiConfig.java
I was originally going to do this for mods using NHlib configs, but figured it would be nice for other mods to have too. Also enables categorized mode for the hodgepodge config, because it was borderline unusable before.
All of the `@Config.RequiresMcRestart` annotations have been moved onto the class, because the end result is the same no matter how many options have it.
Just a simple search bar
> Add a search bar to the mod config gui

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/memory/MixinFMLClientHandler.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/MixinDirection_Memory.java
The patched method creates a int[3] array with coords x y z for every method call
And that method gets called a lot when you have nuclear reactors
> Memory optimization

- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/hax/FastIntCache.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/MixinChunkProviderServer.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/MixinEntityPlayerMP.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/MixinIntCache.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/MixinWorldChunkManager.java
- src/main/resources/META-INF/hodgepodge_at.cfg
Actually multithreading chunks is taking far longer than expected, and fastload has much easier components to merge. Both are off by default, as they may break other mods and especially hybrid servers.
- Fast chunk handling: removes the hard caps of 5 chunks sent per player per tick and 100 chunks unloaded per tick, both are now configurable.
- Fast int cache: rewrite's vanilla's int cache method used it chunk generation to make it threadsafe, faster, and probably less allocation-heavy. Impact will likely be minor until the rest of fastload hits (and without explicit compat it might be worse, so it'll stay off by default until then).
> Merge working parts of fastload

- src/main/java/com/mitchej123/hodgepodge/client/HodgepodgeClient.java
- src/main/java/com/mitchej123/hodgepodge/client/handlers/ClientKeyListener.java
The event handler is only registered if `FixesConfig.speedupAnimations` is true but that event handler is alos used for the fast placing keybind
> fix speedupAnimations setting also disabling fast placing keybind

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinContainerFilingCabinet.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinContainerFilter.java
This fixes two dupes in EU2, one of which involving a Bag of Holding and an Item Filter, the other involving any backpack-esque item and a Filing Cabinet, both due to buggy hotkey logic.
The filter dupe will let you hotkey a Bag of Holding onto the filter in your hotbar while you have it open, and then put ghost items into the "filter" like normal, instead putting them into the Bag of Holding.
This is mitigated by verifying that the slot you are hotkeying onto isn't also the currently active slot.
The Filing Cabinet doesn't cap the item stack size when you hotkey an itemstack to your inventory, allowing you to store two backpacks, pull out the stacked items, put an item in them, unstack them, and pull the item out of both of them.
This is mitigated by modifying the stack size temporarily, …
> feat: patch several dupes in eu2

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinContainerPlayer.java
Merges the mixin patch from https://github.com/GTNewHorizons/BQ3-Thermos-patch
> Merge mixin from BQ3-Thermos-patch mod

- src/main/java/com/mitchej123/hodgepodge/client/DebugScreenHandler.java
If a mod cancels the `RenderGameOverlayEvent.Pre` for `type == DEBUG`, the lists `event.left` and `event.right` will be empty, therefore we need to check the sizes before adding to a specific index.
> fix crash in DebugScreenHandler

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/minefactoryreloaded/MixinBlockRubberSapling.java
Prevent Massive World Destroying Sacred Rubber Tree Generation, downscaling it to a reasonable Mega sized one instead:
Sacred Rubber Tree:
> Prevent Massive World Destroying Sacred Rubber Tree Generation

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerPlayClient_FixHandleSetSlot.java
FixHandleSetSlot checked the length of openContainer even when the packet was for the player's inventory.
This prevented player inventory updates when a server-side gui was open.
To fix this, the existing mixin was split into two and the cancel code was tweaked slightly (it had two targets already).
Before:
After:
closes: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18170
> Split FixHandleSetSlot into container & inv

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinBlockCircleGlyph.java
Fixes a possible AIOOB caused by an int clamp being wrong in Witchery's rendering. This bug is hard to reproduce and not sure exactly where the problem comes from, but there seems to be some kind of edge case, in some combination of mods and things happening, where a glyph's metadata can be above the expected max of 11. Witchery has a clamp that prevents that would prevent that from causing an AIOOB, however the clamp is incorrect and off by one, so this makes it so the clamp at least works and prevents a crash.
See https://github.com/GTNewHorizons/Angelica/issues/778 for the original crash
> Fix off by one int clamp in Witchery's glyph rendering

- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinTileEntityEnderQuarry.java
This removes the need for GTNH's modified version of EU2, where the only changes between the modified version and release are a mitigation for one of the dupes fixed in #438, and to modify the Ender Quarry's storage (set to 200,000,000 instead of 10,000,000).
Currently, it adds one new config option, and you can set the option to 0 to disable it. It defaults to the original value of 10,000,000 instead of the modified version currently in GTNH.
> Configurable ender quarry RF storage

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlePlayServer_FixWrongBlockPlacementCheck.java
Fix block placement distance by players being wrong.
Typical symptom are blocks on the ceiling that disappear shortly after you you placed them. You can't place a block at the ceiling but can remove the block above it. Introduces in the past when Notch splitted of the server. If I'm not wrong, it's fixed in modern Minecraft versions.
Before:
https://github.com/user-attachments/assets/d2c328ec-3442-4a6e-888b-c6792e4b6e09
After:
https://github.com/user-attachments/assets/58d47d67-ea92-4974-904d-a0cfcb93400c
> fix wrong block placement distance check

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
Throwing a RuntimeException here causes all of the early mixins to be skipped if coretweaks isn't loaded
> Fix coretweaks hard-dep

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlePlayServer_FixWrongBlockPlacementCheck.java
Fix https://cdn.discordapp.com/attachments/521008249844269061/1322531840497815593/2024-12-28_12-44-05.mkv?ex=6771e002&is=67708e82&hm=71e512b93955a0133fabe21bedbd0d5628018985d990546bb169fed02f2967ad&
Tested a bit around and got `0.5` as perfect value. It matches the renderer and I'm no longer able to reproduce the issue while building upwards and downwards. Compared to the `1.5` for the digging event `0.5` is perfect for the placing event (It is logical, but it is difficult for me to explain in English).
> fix placing blocks isn't working downwards

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinInventoryCrafting.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18488
> Fix lag when trying to right click items but the interaction fails

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinItemReed.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSoundManager.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinStats.java
- src/main/resources/META-INF/hodgepodge_at.cfg
Example screenshot of the Block stats GUI:
> Display Mod Name under the Item's Name in Item / Block Stat GUI

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/cofhcore/MixinFMLEventHandler.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18239
The issue only happens in SP and was caused by a race condition between the server & client threads. (also wtf it re-initializes this every time a player joins???)
Disregard that the injected method is annotated with `@Mod.EventHandler` it calls it itself in various places.
https://github.com/GTNewHorizons/CoFHCore/blob/4be193afe63bcf108c5ad5abd34da34028434c65/src/main/java/cofh/core/util/FMLEventHandler.java#L38
https://github.com/GTNewHorizons/CoFHCore/blob/4be193afe63bcf108c5ad5abd34da34028434c65/src/main/java/cofh/CoFHCore.java#L191 - this is the one responsible for the race condition
> Fix race condition in COFH's oredict initialization

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinSkinManager$2.java
1. SkinManager store all skin texture in its TextureManager, with ThreadDownloadImageData being image data. Cached skin texture are never flushed (except on game restart).
2. ThreadDownloadImageData holds onto a reference of IImageBuffer, which is a hybrid of binary data sink and onDownloadFinish callback
3. This specific subclass of IImageBuffer holds onto a callback object via a synthetic field generated by compiler, as it's an anonymous class. 
4. This callback object should implement SkinAvailableCallback, whose most notable subclass is EntityPlayerSP, which obviously strongly references its World object
This whole chain of reference creates an obscure way to leak the first client world ever loaded (and possibly more if in multiplayer game). I vaguely recall there was one or two other …
> Fix skin manager leaking client world

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/commands/DebugCommand.java
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/server/MixinDedicatedServer_PauseWhenEmpty.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/server/MixinMinecraftServer_PauseWhenEmpty.java
- src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/IPauseWhenEmpty.java
- src/main/resources/META-INF/hodgepodge_at.cfg
Change from modern: default value of `pause-when-empty-seconds` is 0 which means the server wont pause.
Tested in a dev server with a value of 5.
Ticks stopped after 5 seconds, resumed when there was a connection and then stopped again when empty after 5 seconds.
Added command `/hp pauseWhenEmpty <seconds>`
> Backport 1.20's 'pause-when-empty-seconds' server property

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/cofhcore/MixinBlockHelper.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/minefactoryreloaded/MixinTileEntityBlockBreaker.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/minefactoryreloaded/MixinTileEntityBlockSmasher.java
This PR intents to improve the following mods/items:
- MineFactory Reloaded
- Block smasher
- Block breaker
- Thermal Expansion
- Terrain smasher
This allowes mods to manipulate the output, like EFR that changes the output of ore blocks to raw ore items. -> Make it more realistic, like a player that breaks a block, what it even is intented to be.
From my side this is tested in dev and within my full private pack (200+ mods).
However, someone should test this also in the full GTNH pack, if it breaks any maschine that break blocks or convert them to items. If it makes problems, I can will make the config defaults `false`.
> Improve several simulated block break actions of mods

- src/main/java/com/mitchej123/hodgepodge/mixins/late/minefactoryreloaded/MixinTileEntityBlockSmasher.java
-> got removed falsely via commit d361e088259cdbd8ebe2790d527cdc5b4ce50775 from #478 
This change was important to fix a server crash due NullPointerException from EFR that assumes this isn't null. Reason is that the super method thinks it can't handle it and just return null.
Wasn't able to test again until now after glows changes, and well, it was merged already. That's why this PR.
> ensure drops is not null

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinTileEntityEnderQuarry_FixFreeze.java
This fixes an issue where the Ender Quarry get stuck at a mostly random location and wont continue with anything (soft-lock). The only thing that works at this point is breaking the quarry. placing it and starting again from zero.
The source are a few blocks from mods that either drop nothing *(having a few blocks in mind, but random mods)* or mods that converts their blocks while harvesting *(hello Underground Biomes Construct)*.
To prevent this issue we need to return `true` also in the following (so all available) scenario at the method `harvestBlock`:
- The harvested block has no drops
- The harvested block has unexpected drops
- The harvested block has been harvested by another Entity
New possible effects:
- If the block can't be harvested for some good reason, the drops (if …
> fix extra utilities ender quarry freeze/soft-lock randomly

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/mps/MixinElectricAdapterEU.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/mps/MixinElectricAdapterME.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/mps/MixinElectricAdapterRF.java
Prevent Modular Powersuits from transferring energy of non-mps items in the player's inventory.
For Balancing:
- Prevents MPS from charging equipment too well, effectively making it free to use.
- Prevents MPS Batteries being meaningless as you can hoard energy devices and it will drain from those.
For Players
- Prevent important equipment you plan to use from being drained by MPS
For Fixing:
- Prevents situations where MPS was using energy from modded items without subtracting energy, effectively making it costless
For Modpack Creators
- Allows to define which Energy System MPS should interact with (RF, EU or ME - There are configs for each)
> Modular Powersuits energy methods to only interacts with MPS equipment

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNetHandlerPlayClient_FixEntityAttributesRange.java
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17380.
Reproduction steps:
- A `1.7.10` Minecraft server and client, with `EnderZoo-1.7.10-1.0.15.32.jar`, `Baubles-1.7.10-1.0.1.10`, and `Thaumcraft-1.7.10-4.2.3.5`.
- Start the server and client. After joining the server, place some concussion creepers using the spawn egg.
- Close the server with the command `stop`, and set the L32 `concussionCreeperEnabled` in `server/config/enderzoo/EnderZoo.cfg` to `false`, then restart the server.
- Join the server again.
- The client should crash with the error message: `java.lang.IllegalArgumentException: Default value cannot be lower than minimum value!`.
See also:
- https://bugs.mojang.com/browse/MC-150405
- https://github.com/MinecraftForge/MinecraftForge/commit/05f4f5ec775fbb …
> fix entity attributes range

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thermaldynamics/MixinTileFluidDuctSuper.java
Cancels and destroys attempts to create invalid fluid duct networks instead of crashing with CastClassException.
Thermal frequently casts objects without verifying if they are valid instances of the target class, which is why this issue persists. Unfortunately, this won’t be the last time it occurs. If it were FOSS, fixing it would be trivially easy.
> Prevent CastClassException on invalid duct network

- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinBlockStaticLiquid.java
- src/main/resources/META-INF/hodgepodge_at.cfg
In my world lava constantly loads chunks, causing quite a big performance hit. It's not so big that it's causing tps lag, but at the same time it's taking up 10-20% of my tick time, so it's low hanging fruit.
I've redirected several `World.getBlock` + analogues to check if the chunk is loaded first, and if it's not, bail. This change is fairly low risk, since this logic is only used to set flammable things around lava on fire.
Before:
https://spark.lucko.me/kUlsa23drS
BlockLiquidStatic only calls the update method, which only contains the fire logic for lava.
After:
https://spark.lucko.me/xjzUlFbAka
> Prevent lava from loading chunks

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinLanguageRegistry.java
Currently it looks at each loaded mod and then examines the containing file - which means for any container that has multiple mods the same jar will be examined multiple times.
Gregtech, for example:
```
$ grep "Found translations in gregtech" fml-client-latest.log | wc -l
15
```
> Stop searching the same file multiple times for languages.

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinItemGlassBottle.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17552
Original code (caused any block with the `water` material to give water, of which many modded fluid blocks have this material):
> Fix Glass Bottles filling with water from some other Fluid blocks

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinItemHealingAxe.java
Currently the healing axe doesn't actually heal mobs like its description says it should because of a bug/typo, the original code has `target.getHealth() < target.getHealth()` as a condition to heal
The description says "it will take some health from you and use it to heal the target, with a slight bonus", considering what pack this is i interpreted that as taking a quarter heart less than it heals
I'm a pretty new player and I don't have access to the dev discord channels so I'm not sure how exactly this will affect balance so I'll leave discussing that to the actual developers.
> Fix the healing axe not healing entities when attacking them

- build.gradle.kts
- src/main/java/com/mitchej123/hodgepodge/config/TweaksConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/sync/MixinTEReactor.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/ic2/sync/MixinTEReactorChamber.java
Normally they randomize their start/stop timers, preventing nuke setups from using precise timings. Any setup with more than one reactor needs to account for the reactors having up to a 2s variance in start or stop times, requiring downtime or wasting fuel. This tweak is off by default, unless there's consensus to have it in the pack.
> Add option to synchronize IC2 reactors

- src/main/java/com/mitchej123/hodgepodge/asm/AsmTransformers.java
- src/main/java/com/mitchej123/hodgepodge/asm/transformers/mc/SpeedupObjectIntIdentityMapTransformer.java
- src/main/java/com/mitchej123/hodgepodge/config/ASMConfig.java
- src/main/java/com/mitchej123/hodgepodge/util/FastUtilsObjectIntIdentityHashMap.java
- src/main/java/com/mitchej123/hodgepodge/util/ProperObjectIntIdentityMap.java
Also add a FastUtilsObjectIntIdentityHashMap subclass of IdentityHashMap<Object, Integer> because that was used for the variable instead of Map<>
This showed up on one of my profiles of Angelica & DH as larger than it should be IMHO, this should be no worse than the default impl and likely better
> Swap out ObjectIntIdentityMap with ProperObjectIntIdentityMap to avoid Box/Unbox of ints

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunkCoordIntPair_BetterHash.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunkCoordIntPair_FixAllocations.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinChunkCoordinates_BetterHash.java
Was causing trouble (collisions) with the large number of chunks being loaded for Distant Horizons
> Better hashcode for ChunkCoordIntPair

- build.gradle.kts
- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinGameSettings_ReduceRenderDistance.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinWorldUpdateEntities.java
Disables a conflicting (and identical) mixin when ArchaicFix is installed, and clamps render distance when Angelica or Optifine is missing. Vanilla by itself doesn't check if render distance is in range, so if you install Angelica, crank the render distance above 16, and uninstall Angelica, you'll get runtime crashes until you turn the render distance back down.
Requires https://github.com/embeddedt/ArchaicFix/pull/142
> ArchaicFix and Angelica (removal) compat

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/flatid/MixinBlock.java
What it says on the tin - fixes a crash with Buildcraft and probably other mods too.
> Catch null and never registered cases when embedding block IDs

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinContainer_FixShiftRecursion.java
Backports the 1.12 version instead of recursively calling slotClick
I believe this also fixes the issue where if you shift click a crafting slot and the output changes (from running out of an input) and the craft would continue when it should have stopped.
Test craft: Unstable Ingot  
Latest GTNH Nightly  
Before:
After:
> Remove recursive slotClick calls when shift clicking a slot

- build.gradle.kts
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/flatid/MixinBlock.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/fastload/flatid/MixinFMLControlledNamespacedRegistry.java
- src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/BlockExt_ID.java
Namespace the injected method for embedding block IDs, to avoid collisions with other mods.
I probably should have predicted this would be an issue...
Fixes #529
> Namespace injected method

- src/main/java/com/mitchej123/hodgepodge/util/VoxelMapCacheMover.java
Hodgepodge will try to rename voxelmap cache files to .data regardless of whether the resulting file already exists, which can result in some heavy log spam (upwards of 3,000 lines in some cases) due to the resulting FileAlreadyExistsException.
This adds a check to see whether:
- The file exists and either:
- the two files are identical, or
- the source file is newer (which could happen if hodgepodge was temporarily disabled)
If this fails, it will replace the preexisting file
> ignore preexisting voxelmap data files when trying to change ext

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinItemEthericSword.java
Prevents the Etheric Sword from losing Durability when breaking Blocks (like Cobweb)
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19756
Before (After breaking a Block):
After (After breaking a Block):
> Make Etheric Sword truly Unbreakble

- src/main/java/com/mitchej123/hodgepodge/config/ASMConfig.java
It's not stable and causes serious issues on leaving/reentering a world.
Needs some work and testing and can be re-enabled by default when stable.
> Disable Embed IDs by default

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/extrautilities/MixinTileEnderCollector.java
fixes the crash loop when Ender Collector is placed above auto-dropping Blocks.
Currently included Blocks:
- Open Crate (Botania)
- Item Valve (SFM)
- Rapid Item Valve (SFM)
- Item Grate (Thaumcraft)
closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18154
Still working on normal Inventories:
Not working on mentioned Blocks:
> Fix Crash Loop with EU Ender Collector

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/fml/MixinEventBus.java
while this isn't a memory leak because the map has weak keys and values. This map keeps growing with potentially thousands of events
> Remove unregistered events from MixinEventBus.listenerOwners

- src/main/java/com/mitchej123/hodgepodge/asm/AsmTransformers.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/TargetedMod.java
Disable SPEEDUP_ORE_DICTIONARY and ADD_SIMULATION_DISTANCE which doesn't work properly on ultramine
Also closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/19924
> Disable some patches when ultramine present

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
This updates the comment of the configuration node `fixes.fixTimeCommandWithGC` to refer to Galacticraft by its full name, instead of using the abbreviation "GC". The motivation behind this is simply to prevent confusion. A user of this mod may not know what "GC" refers to if he doesn't have Galacticraft installed. Personally, I thought it was referring to garbage collection, until I looked at the mixin code.
> Refer to Galacticraft by its name instead of an abbreviation

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinNBTTagList_speedup.java
- src/main/java/com/mitchej123/hodgepodge/mixins/interfaces/NBTTagListExt.java
> Delete unnecessary invoker interface for MixinNBTTagList_speedup

- addon.gradle
- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEnumChatFormatting_FastFormat.java
- src/main/java/com/mitchej123/hodgepodge/util/StringUtil.java
- src/test/java/hodgepodge/StringUtilsTest.java
> Speedup `EnumChatFormatting.getTextWithoutFormattingCodes`

- src/main/java/com/mitchej123/hodgepodge/mixins/early/forge/MixinForgeHooks_ModernPickBlock.java
This should now match the modern vanilla behaviour.
When picking a block it will first try to find an empty slot, then one with an item that is not enchanted, then the current slot.
> Improve pick block

- src/main/java/com/mitchej123/hodgepodge/core/HodgepodgeCore.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/fml/MixinEventBus_DebugRegistration.java
- src/main/java/com/mitchej123/hodgepodge/mixins/preinit/MixinLoadController_logModTimes.java
- src/main/java/com/mitchej123/hodgepodge/util/FileLogger.java
`-Dhodgepodge.logEventTimes=true`
spits out a file that looks like this :
```
Registered event class : logisticspipes.commands.chathelper.LPChatListener
Methods Visited : 32
Handlers found : 2
Time elapsed : 3ms
Total Time elapsed : 1700ms
Registered event class : net.malisis.doors.event.DoorEventHandlerClient
Methods Visited : 20
Handlers found : 2
Time elapsed : 0ms
Total Time elapsed : 1700ms
Registered event class : modtweaker2.ClientEvents
Methods Visited : 19
Handlers found : 1
Time elapsed : 0ms
Total Time elapsed : 1701ms
Registered event class : net.bdew.neiaddons.network.ServerHandler
Methods Visited : 170
Handlers found : 2
Time elapsed : 4ms
Total Time elapsed : 1705ms
```
> add debug flag to log time to register forge event handlers

- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
archaix fix is optimizing the creative tab search so we don't need to disable it to prevent crashing anymore
> stop disabling the creative search bar if archaix fix is present

- README.md
- src/main/java/com/mitchej123/hodgepodge/Compat.java
- src/main/java/com/mitchej123/hodgepodge/Hodgepodge.java
- src/main/java/com/mitchej123/hodgepodge/HodgepodgeEventHandler.java
- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/util/TravellersGear.java
Return items placed in Traveller's Gear slots after the mod is removed when players log in.
Sends messages to the log that start with "[Hodgepodge]: [TG Recovery]".
Removes players from the TG items file after returning items. Deletes it if it's empty.
Automatically disables itself on servers after deleting the TG items file.
Clients leave it on to allow for joining multiple SP worlds with TG items.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/20458
> Return items stored in Travellers Gear slots after the mod is uninstalled.

- dependencies.gradle
- src/main/java/com/mitchej123/hodgepodge/config/SpeedupsConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinCraftingManager.java
Makes recipe matching faster by re-ordering the recipe list when there is a match to move the matched recipe at the start of the list thus making subsequent matches faster.
> Cache last matching crafting recipe

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/thaumcraft/MixinUtils.java
Add a check for the mod before trying to get the class to avoid issues on modern java due bad practice.
Ref: https://discord.com/channels/181078474394566657/603348502637969419/1403832924322795632
Original:
```
public static boolean isEETransmutionItem(Item item) {
try {
String itemClass = "com.pahimar.ee3.item.ITransmutationStone";
Class ee = Class.forName(itemClass);
if(ee.isAssignableFrom(item.getClass())) {
return true;
}
} catch (Exception var3) {
;
}
return false;
}
```
> fix thaumcraft check for ee3

- src/main/java/com/mitchej123/hodgepodge/mixins/early/minecraft/MixinEntityRenderer_NightVisionFade.java
If a forge AT widens the visibility of the method, when we overwrite it to make it private it will cause a crash because it is not allowed to decrease visibility. Making the overwrite public directly solves that issue.
fix crash : https://github.com/GTNewHorizons/Hodgepodge/pull/598#issuecomment-3172963964
> Fix night vision mixin crash with forge AT

- src/main/java/com/mitchej123/hodgepodge/config/FixesConfig.java
- src/main/java/com/mitchej123/hodgepodge/mixins/Mixins.java
- src/main/java/com/mitchej123/hodgepodge/mixins/late/witchery/MixinEntityDemon.java
This PR Adds a Mixin to prevent the Witchery Demon's trading menu from opening when right-clicking while holding shift. This allows for certain items to work on demons, such as the Soul Vial from Ender IO.
A new setting was added to enable/disable this fix (Default: True).
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17040
> Fix Witchery Demon not able to be put in Ender IO Soul Vial
